const assert=require('node:assert/strict')
const path=require('node:path').resolve(process.argv[2])
const {project}=require(path+'/board.js')
const {validateDrafts}=require(path+'/validation.js')
const {factsInWindow}=require(path+'/timeline.js')
const ops=[]
const add=(type,payload,extra={})=>{const action={id:`a${ops.length}`,clock:ops.length+1,at:'2026-09-29T00:00:00Z',actor:'analyst',author:'Analyst',boardId:'board',type,payload,...extra};ops.push(action);return action.id}
const graph=()=>project('board',ops).data
const item=()=>graph().facts[0].assertions.find(a=>a.id==='e')
add('entity.add',{id:'a',name:'IP',kind:'IP',x:40,y:80})
add('entity.add',{id:'b',name:'File',kind:'File'})
add('source.add',{id:'s',title:'Raw logs',source_kind:'primary',uri:'repo/logs.json',excerpt:'{"EventId":"42"}'})
add('fact.add',{id:'f',subject_id:'a',object_id:'b',predicate:'reads'})
add('assertion.add',{id:'e',fact_id:'f',source_id:'s',stance:'supports',note:'Read event 42',locator:'EventId=42',valid_from:'2026-09-28T10:00:00Z'})
assert.equal(item().review_status,'unconfirmed')
assert.equal(graph().facts[0].truth_state,'unknown')
const review=()=>({id:'e',review_status:'confirmed',expected_revision:item().revision,expected_source_revision:graph().sources[0].revision,review_note:'Checked original event'})
validateDrafts(graph(),[{type:'assertion.review',payload:review()}])
add('assertion.review',review())
assert.equal(item().review_status,'confirmed')
assert.equal(graph().facts[0].truth_state,'supported')
add('assertion.update',{id:'e',note:'Corrected read'})
assert.equal(item().review_status,'unconfirmed')
assert.throws(()=>validateDrafts(graph(),[{type:'assertion.review',payload:{...review(),expected_revision:'old'}}]),/revision/)
add('assertion.review',review())
add('source.update',{id:'s',excerpt:'Changed original'})
assert.equal(item().review_status,'unconfirmed')
add('assertion.review',review())
add('assertion.retract',{id:'e'})
assert.equal(graph().facts[0].truth_state,'unknown')
add('assertion.restore',{id:'e'})
assert.equal(item().retracted_at,null)
assert.equal(item().review_status,'unconfirmed')
add('source.update',{id:'s',source_kind:'secondary'})
assert.throws(()=>validateDrafts(graph(),[{type:'assertion.review',payload:review()}]),/primary source/)
add('source.update',{id:'s',source_kind:'primary'})
add('assertion.review',review())
add('assertion.add',{id:'other',fact_id:'f',source_id:'s',stance:'refutes',note:'Refuting event',locator:'EventId=43',valid_from:'2026-09-29T10:00:00Z'})
const other=graph().facts[0].assertions.find(a=>a.id==='other')
add('assertion.review',{...review(),id:'other',expected_revision:other.revision})
assert.equal(graph().facts[0].truth_state,'disputed')
assert.equal(factsInWindow(graph().facts,'2026-09-28T00:00:00Z','2026-09-28T23:59:59Z')[0].truth_state,'supported')
assert.throws(()=>validateDrafts(graph(),[{type:'source.delete',payload:{id:'s'}}]),/referenced/)
assert.throws(()=>validateDrafts(graph(),[{type:'assertion.update',payload:{id:'e',valid_to:'2020-01-01T00:00:00Z'}}]),/after start/)
const move=add('entity.position',{id:'a',x:200,y:300})
const rename=add('entity.update',{id:'a',name:'Renamed'})
add('action.undo',{action_ids:[move,rename]})
assert.equal(graph().entities.find(e=>e.id==='a').name,'IP')
assert.equal(graph().entities.find(e=>e.id==='a').position.x,40)
add('action.redo',{action_ids:[move,rename]})
assert.equal(graph().entities.find(e=>e.id==='a').name,'Renamed')
add('entity.merge',{source_id:'a',target_id:'b'})
assert.equal(graph().facts[0].assertions.length,2,'merge must retain self-relations and their evidence')
assert.equal(graph().facts[0].truth_state,'unknown')
console.log('Review transitions, primary-source requirements, revisions, invalidation, range status, grouped undo/redo and evidence-preserving merge passed')
